services:
  hitalent:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hitalent
    ports: 
      - "${FASTAPI_PORT}:8000"
    command: "uvicorn --factory src.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres:16
    container_name: postgresdb_hitalent
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_hitalent
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres

volumes:
  pgdata:
